spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:./build/h2db/db/ONBOARDING;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS ONBOARDING
    username: sa
    password: sa
  h2:
    console:
      enabled: true